"""Render the digest to HTML and deliver it.

Sections are driven by the topic list, so a new topic in the config shows up here
with no code change. Email HTML is deliberately inline-styled and table-free —
that is what survives Gmail/Outlook.
"""

from __future__ import annotations

import datetime as dt
import html
import os

import requests

CSS_BODY = ("font-family:-apple-system,BlinkMacSystemFont,'Segoe UI','PingFang SC',"
            "'Microsoft YaHei',Helvetica,sans-serif;max-width:660px;margin:0 auto;"
            "padding:24px;color:#1f2328;line-height:1.55;")


def _e(s) -> str:
    return html.escape(str(s or ""), quote=True)


def _section(title, items):
    if not items:
        return ""
    rows = "".join(
        f"""<div style="margin:0 0 16px 0;">
              <a href="{_e(it.get('url', '#'))}"
                 style="color:#0969da;font-weight:600;text-decoration:none;font-size:15px;">
                {_e(it.get('title'))}</a>
              <div style="color:#57606a;font-size:14px;margin-top:3px;">
                {_e(it.get('summary'))}</div>
            </div>"""
        for it in items
    )
    return _heading(title) + rows


def _heading(title):
    return (f"""<h2 style="font-size:16px;margin:26px 0 12px;padding-bottom:6px;"""
            f"""border-bottom:2px solid #eaeef2;">{_e(title)}</h2>""")


def _countdown(deadlines, title="Countdown"):
    if not deadlines:
        return ""
    rows = "".join(
        f"""<li style="margin-bottom:5px;font-size:14px;"><b>{_e(d['name'])}</b>
            — {_e(d['date'])} (<span style="color:{'#cf222e' if d['days_left'] <= 30 else '#57606a'};">
            {d['days_left']} days left</span>)</li>"""
        for d in deadlines
    )
    return _heading(title) + f"""<ul style="padding-left:18px;margin:0;">{rows}</ul>"""


def _tickers(rows, title="Markets"):
    if not rows:
        return ""
    out = ""
    for s in rows:
        pct = s.get("change_pct")
        badge = ""
        if pct is not None:
            badge = (f"""<span style="color:{'#cf222e' if pct < 0 else '#1a7f37'};"""
                     f"""font-weight:600;">{pct:+.2f}%</span>""")
        close = (f"{s.get('close')} {s.get('currency', '')}".strip()
                 if s.get("close") is not None else "—")
        news = "".join(
            f"""<div style="font-size:13px;margin:3px 0 0 14px;">·
                  <a href="{_e(n.get('url', '#'))}"
                     style="color:#57606a;text-decoration:none;">{_e(n.get('title'))}</a>
                </div>"""
            for n in s.get("news", [])
        )
        out += (f"""<div style="margin:0 0 12px 0;font-size:14px;">"""
                f"""<b>{_e(s.get('ticker'))}</b>&nbsp; {_e(close)}&nbsp; {badge}{news}</div>""")
    return _heading(title) + out


def render_html(digest: dict, title: str) -> str:
    """`digest` is the object written to data/YYYY-MM-DD.json."""
    date_str = digest.get("date") or dt.date.today().isoformat()
    parts = []
    for sec in digest.get("sections", []):
        kind = sec.get("kind", "items")
        if kind == "tickers":
            parts.append(_tickers(sec.get("rows", []), sec.get("title", "Markets")))
        elif kind == "countdown":
            parts.append(_countdown(sec.get("rows", []), sec.get("title", "Countdown")))
        else:
            parts.append(_section(sec.get("title", ""), sec.get("items", [])))

    headline = digest.get("headline", "")
    headline_html = (
        f"""<div style="background:#f6f8fa;border-radius:8px;padding:14px 16px;
             font-size:15px;margin-bottom:8px;">{_e(headline)}</div>"""
        if headline else "")

    return f"""<!doctype html><html><head><meta charset="utf-8">
      <meta name="viewport" content="width=device-width,initial-scale=1"></head>
      <body style="{CSS_BODY}">
        <h1 style="font-size:22px;margin:0 0 2px;">{_e(title)}</h1>
        <div style="color:#8c959f;font-size:13px;margin-bottom:18px;">{_e(date_str)}</div>
        {headline_html}
        {''.join(parts)}
        <div style="color:#8c959f;font-size:12px;margin-top:32px;
             border-top:1px solid #eaeef2;padding-top:10px;">
          Generated by <a href="https://github.com/topics/open-digest"
          style="color:#8c959f;">open-digest</a>
        </div>
      </body></html>"""


def render_text(digest: dict, title: str) -> str:
    """Plain-text fallback — also what ``--print`` writes to the terminal."""
    lines = [title, digest.get("date", ""), ""]
    if digest.get("headline"):
        lines += [digest["headline"], ""]
    for sec in digest.get("sections", []):
        lines.append(f"## {sec.get('title', '')}")
        if sec.get("kind") == "tickers":
            for s in sec.get("rows", []):
                pct = s.get("change_pct")
                move = f" ({pct:+.2f}%)" if pct is not None else ""
                lines.append(f"  {s.get('ticker')}: {s.get('close')}{move}")
        elif sec.get("kind") == "countdown":
            for d in sec.get("rows", []):
                lines.append(f"  {d['name']} — {d['date']} ({d['days_left']} days left)")
        else:
            for it in sec.get("items", []):
                lines += [f"  • {it['title']}", f"    {it['summary']}", f"    {it['url']}"]
        lines.append("")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# Delivery
# --------------------------------------------------------------------------
def deliver(html_body: str, subject: str, cfg: dict):
    """Dispatch on ``delivery.method``. Add a method = add a branch."""
    method = (cfg.get("method") or "file").lower()
    if method == "resend":
        return _send_resend(html_body, subject, cfg)
    if method == "webhook":
        return _send_webhook(html_body, subject, cfg)
    if method == "file":
        return None  # main.py already wrote the preview file
    raise ValueError(f"unknown delivery method {method!r} "
                     "(expected: resend | webhook | file)")


def _send_resend(html_body, subject, cfg):
    key = os.environ.get("RESEND_API_KEY")
    if not key:
        raise RuntimeError("RESEND_API_KEY is not set (put it in .env or export it)")
    to = cfg.get("to")
    if not to:
        raise ValueError("delivery.to is required when method is 'resend'")
    r = requests.post(
        "https://api.resend.com/emails",
        headers={"Authorization": f"Bearer {key}"},
        json={"from": cfg.get("from", "onboarding@resend.dev"),
              "to": to if isinstance(to, list) else [to],
              "subject": subject, "html": html_body},
        timeout=20,
    )
    r.raise_for_status()
    print(f"   [ok] email sent (id={r.json().get('id')})")


def _send_webhook(html_body, subject, cfg):
    """POST to Slack/Discord/anything. Sends text — most webhooks reject HTML."""
    url = cfg.get("url") or os.environ.get("DIGEST_WEBHOOK_URL")
    if not url:
        raise ValueError("delivery.url (or DIGEST_WEBHOOK_URL) is required "
                         "when method is 'webhook'")
    r = requests.post(url, json={"text": f"*{subject}*\n\n{cfg.get('_text', '')}"},
                      timeout=20)
    r.raise_for_status()
    print("   [ok] webhook delivered")
